import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import QRCode from 'qrcode';
import webpush from 'web-push';

const safeText = (value, max = 500) => String(value || '').trim().slice(0, max);
const futureDate = (value) => { const date = new Date(value); return Number.isFinite(date.getTime()) && date.getTime() > Date.now() - 5 * 60000 ? date : null; };
const digestCode = (pickupId, code, secret) => crypto.createHmac('sha256', secret).update(`${pickupId}:${code}`).digest('hex');
const timingEqual = (a, b) => { const left = Buffer.from(String(a)); const right = Buffer.from(String(b)); return left.length === right.length && crypto.timingSafeEqual(left, right); };

const base32Alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
const encodeBase32 = (buffer) => {
  let bits = ''; for (const byte of buffer) bits += byte.toString(2).padStart(8, '0');
  return bits.match(/.{1,5}/g).map((chunk) => base32Alphabet[parseInt(chunk.padEnd(5, '0'), 2)]).join('');
};
const decodeBase32 = (value) => {
  const bits = String(value || '').toUpperCase().replace(/=|\s/g, '').split('').map((char) => base32Alphabet.indexOf(char).toString(2).padStart(5, '0')).join('');
  return Buffer.from((bits.match(/.{8}/g) || []).map((byte) => parseInt(byte, 2)));
};
const totp = (secret, counter = Math.floor(Date.now() / 30000)) => {
  const buffer = Buffer.alloc(8); buffer.writeBigUInt64BE(BigInt(counter));
  const hash = crypto.createHmac('sha1', decodeBase32(secret)).update(buffer).digest(); const offset = hash[19] & 15;
  return String((((hash[offset] & 127) << 24) | ((hash[offset + 1] & 255) << 16) | ((hash[offset + 2] & 255) << 8) | (hash[offset + 3] & 255)) % 1000000).padStart(6, '0');
};
export const verifyTotp = (secret, code) => /^\d{6}$/.test(String(code || '')) && [-1, 0, 1].some((window) => timingEqual(totp(secret, Math.floor(Date.now() / 30000) + window), code));

const articleDefaults = [
  { id: 'KB-WIFI', category: 'IT & network', title: 'Campus Wi-Fi quick checks', summary: 'Reconnect safely before reporting a network issue.', body: 'Turn Wi-Fi off and on, forget and rejoin the campus network, then confirm whether the problem affects one device or everyone nearby. Never include your password in a report.', tags: ['wifi', 'internet', 'network'] },
  { id: 'KB-PROJECTOR', category: 'IT & network', title: 'Projector is not displaying', summary: 'Check input, cable, and room controls.', body: 'Confirm the projector is powered on, select the correct HDMI input, reseat the cable, and try duplicate-display mode. Report the room number and any light or error code you see.', tags: ['projector', 'display', 'classroom'] },
  { id: 'KB-LEAK', category: 'Plumbing', title: 'Water leak safety', summary: 'Protect people first and report the exact source.', body: 'Keep people away from wet electrical equipment. If safe, identify the closest room or fixture and add a wide photo. For rapidly flowing water, contact campus security as well as submitting a high-impact report.', tags: ['water', 'leak', 'plumbing'] },
  { id: 'KB-ID', category: 'Lost & found', title: 'Lost campus ID or bank card', summary: 'Block access and payments before searching.', body: 'Freeze any bank card immediately. Contact campus services to suspend a lost ID, then create a lost-item report without posting the full card number publicly.', tags: ['id', 'card', 'wallet', 'lost'] },
];

export async function registerAdvancedFeatures(app, deps) {
  const { auth, adminOnly, readDb, mutateDb, makeId, now, notify, addAudit, staffRole, cleanAttachments, sendEmailMessage, jwt, jwtSecret, root } = deps;
  let vapidPublicKey = process.env.VAPID_PUBLIC_KEY; let vapidPrivateKey = process.env.VAPID_PRIVATE_KEY;
  if (!vapidPublicKey || !vapidPrivateKey) { const keyFile = process.env.VAPID_KEY_FILE ? path.resolve(process.env.VAPID_KEY_FILE) : path.join(root, 'data', '.local-vapid.json'); try { const saved = JSON.parse(await fs.readFile(keyFile, 'utf8')); vapidPublicKey = saved.publicKey; vapidPrivateKey = saved.privateKey; } catch { const generated = webpush.generateVAPIDKeys(); vapidPublicKey = generated.publicKey; vapidPrivateKey = generated.privateKey; await fs.mkdir(path.dirname(keyFile), { recursive: true }); await fs.writeFile(keyFile, JSON.stringify({ ...generated, generatedAt: now() }, null, 2), { mode: 0o600 }); await mutateDb((db) => addAudit(db, 'push.local_keys_generated', 'SYSTEM')); } }
  const vapidReady = Boolean(vapidPublicKey && vapidPrivateKey);
  webpush.setVapidDetails(process.env.VAPID_SUBJECT || 'mailto:support@deltacare.local', vapidPublicKey, vapidPrivateKey);

  const pushUser = async (userId, payload) => {
    if (!vapidReady) return { sent: 0, failed: 0, configured: false };
    const db = await readDb(); const subscriptions = db.pushSubscriptions.filter((item) => item.userId === userId && item.active !== false); let sent = 0; let failed = 0; const expired = [];
    await Promise.all(subscriptions.map(async (item) => { try { await webpush.sendNotification(item.subscription, JSON.stringify(payload), { TTL: 86400 }); sent++; } catch (error) { failed++; if ([404, 410].includes(error.statusCode)) expired.push(item.id); } }));
    if (expired.length) await mutateDb((latest) => { latest.pushSubscriptions.forEach((item) => { if (expired.includes(item.id)) item.active = false; }); });
    return { sent, failed, configured: true };
  };
  app.locals.pushUser = pushUser;

  const runReminders = (db) => {
    const created = []; const seen = new Set(db.reminders.map((item) => item.dedupeKey)); const current = Date.now();
    db.issues.filter((issue) => issue.sla?.dueAt && !['resolved', 'closed'].includes(issue.status)).forEach((issue) => {
      const hours = (new Date(issue.sla.dueAt).getTime() - current) / 3600000; const band = hours < 0 ? 'overdue' : hours <= 4 ? 'due_soon' : null; const key = band && `issue:${issue.id}:${band}`;
      if (band && !seen.has(key) && issue.reporterId !== 'ANONYMOUS') { const title = band === 'overdue' ? 'Report needs follow-up' : 'Report update due soon'; const message = `${issue.id} (${issue.title}) is ${band === 'overdue' ? 'past its service target' : 'approaching its service target'}.`; db.reminders.unshift({ id: makeId('REM'), dedupeKey: key, userId: issue.reporterId, entityType: 'issue', entityId: issue.id, title, message, status: 'sent', createdAt: now() }); notify(db, issue.reporterId, title, message, 'issue', issue.id); created.push(key); }
    });
    db.pickups.filter((pickup) => pickup.status === 'scheduled').forEach((pickup) => { const hours = (new Date(pickup.scheduledAt).getTime() - current) / 3600000; const band = hours < -1 ? 'missed' : hours >= 0 && hours <= 24 ? 'tomorrow' : null; const key = band && `pickup:${pickup.id}:${band}`; if (band && !seen.has(key)) { const title = band === 'missed' ? 'Pickup needs rescheduling' : 'Pickup reminder'; const message = band === 'missed' ? 'Your item pickup time has passed. Choose a new time in DeltaCare.' : `Your collection is scheduled for ${new Date(pickup.scheduledAt).toLocaleString('en-IN')}.`; db.reminders.unshift({ id: makeId('REM'), dedupeKey: key, userId: pickup.userId, entityType: 'lostFound', entityId: pickup.itemId, title, message, status: 'sent', createdAt: now() }); notify(db, pickup.userId, title, message, 'lostFound', pickup.itemId); created.push(key); } });
    return created;
  };

  app.get('/api/capabilities', auth, async (_req, res) => { const db = await readDb(); res.json({ push: { configured: vapidReady, publicKey: vapidPublicKey }, identity: { mfa: true, sso: Boolean(process.env.OIDC_ISSUER && process.env.OIDC_CLIENT_ID), passkeys: false }, uploads: { provider: process.env.UPLOAD_PROVIDER || 'inline', antivirus: process.env.CLAMAV_HOST ? 'clamav' : 'built-in-signature' }, database: { provider: 'local-json' }, pickupLocations: db.settings.pickupLocations }); });

  app.post('/api/push/subscriptions', auth, async (req, res) => { const subscription = req.body?.subscription; if (!subscription?.endpoint || !subscription?.keys?.p256dh || !subscription?.keys?.auth) return res.status(400).json({ message: 'A valid browser push subscription is required.' }); const item = await mutateDb((db) => { let existing = db.pushSubscriptions.find((entry) => entry.subscription.endpoint === subscription.endpoint); if (!existing) { existing = { id: makeId('PSH'), userId: req.user.id, subscription, userAgent: safeText(req.headers['user-agent'], 200), active: true, createdAt: now() }; db.pushSubscriptions.push(existing); } else { existing.userId = req.user.id; existing.subscription = subscription; existing.active = true; existing.updatedAt = now(); } addAudit(db, 'push.subscribed', req.user.id, { subscriptionId: existing.id }); return existing; }); res.status(201).json({ subscription: { id: item.id, active: item.active } }); });
  app.delete('/api/push/subscriptions', auth, async (req, res) => { await mutateDb((db) => { db.pushSubscriptions.filter((item) => item.userId === req.user.id && (!req.body?.endpoint || item.subscription.endpoint === req.body.endpoint)).forEach((item) => { item.active = false; }); addAudit(db, 'push.unsubscribed', req.user.id); }); res.json({ message: 'Push notifications disabled.' }); });
  app.post('/api/push/test', auth, async (_req, res) => { const result = await pushUser(_req.user.id, { title: 'DeltaCare notifications are ready', body: 'You will receive important report and pickup updates here.', url: '/app/notifications' }); res.json(result); });

  app.post('/api/auth/mfa/verify', async (req, res) => { const challengeId = safeText(req.body.challengeId, 100); const code = safeText(req.body.code, 10); try { const session = await mutateDb((db) => { const challenge = db.authChallenges.find((item) => item.id === challengeId && !item.used && item.expiresAt > now()); const user = challenge && db.users.find((item) => item.id === challenge.userId); if (!challenge || !user?.security?.mfaSecret || !verifyTotp(user.security.mfaSecret, code)) throw new Error('The verification code is invalid or expired.'); challenge.used = true; const created = { id: makeId('SES'), userId: user.id, createdAt: now(), expiresAt: new Date(Date.now() + 7 * 86400000).toISOString(), mfa: true }; db.sessions.push(created); addAudit(db, 'session.created_mfa', user.id); return { session: created, user }; }); const token = jwt.sign({ uid: session.user.id, sid: session.session.id }, jwtSecret, { expiresIn: '7d' }); res.cookie('deltacare_session', token, { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', maxAge: 7 * 86400000 }); const { passwordHash, security, ...publicProfile } = session.user; res.json({ user: publicProfile }); } catch (error) { res.status(401).json({ message: error.message }); } });
  app.post('/api/security/mfa/setup', auth, async (req, res) => { const secret = encodeBase32(crypto.randomBytes(20)); const issuer = 'DeltaCare'; const uri = `otpauth://totp/${issuer}:${encodeURIComponent(req.user.email)}?secret=${secret}&issuer=${issuer}&algorithm=SHA1&digits=6&period=30`; await mutateDb((db) => { const user = db.users.find((item) => item.id === req.user.id); user.security = { ...(user.security || {}), pendingMfaSecret: secret }; addAudit(db, 'mfa.setup_started', user.id); }); res.json({ secret, uri, qr: await QRCode.toDataURL(uri, { width: 220, margin: 1 }) }); });
  app.post('/api/security/mfa/enable', auth, async (req, res) => { try { await mutateDb((db) => { const user = db.users.find((item) => item.id === req.user.id); const secret = user.security?.pendingMfaSecret; if (!secret || !verifyTotp(secret, req.body.code)) throw new Error('Enter the current six-digit code from your authenticator app.'); user.security = { ...user.security, mfaEnabled: true, mfaSecret: secret, pendingMfaSecret: undefined, enabledAt: now() }; addAudit(db, 'mfa.enabled', user.id); }); res.json({ message: 'Multi-factor authentication is enabled.' }); } catch (error) { res.status(400).json({ message: error.message }); } });
  app.post('/api/security/mfa/disable', auth, async (req, res) => { try { await mutateDb((db) => { const user = db.users.find((item) => item.id === req.user.id); if (!user.security?.mfaSecret || !verifyTotp(user.security.mfaSecret, req.body.code)) throw new Error('Enter a current authenticator code.'); user.security = { mfaEnabled: false, disabledAt: now() }; addAudit(db, 'mfa.disabled', user.id); }); res.json({ message: 'Multi-factor authentication is disabled.' }); } catch (error) { res.status(400).json({ message: error.message }); } });

  app.get('/api/knowledge', auth, async (req, res) => { const db = await readDb(); const query = safeText(req.query.q, 100).toLowerCase(); let articles = db.knowledgeBase.filter((item) => item.published !== false); if (query) articles = articles.filter((item) => `${item.title} ${item.summary} ${item.body} ${(item.tags || []).join(' ')}`.toLowerCase().includes(query)); if (req.query.category) articles = articles.filter((item) => item.category === req.query.category); res.json({ articles }); });
  app.post('/api/admin/knowledge', auth, adminOnly, async (req, res) => { if (!safeText(req.body.title, 120) || !safeText(req.body.body, 5000)) return res.status(400).json({ message: 'Title and article content are required.' }); const article = await mutateDb((db) => { const item = { id: makeId('KB'), title: safeText(req.body.title, 120), category: safeText(req.body.category, 80) || 'General', summary: safeText(req.body.summary, 300), body: safeText(req.body.body, 5000), tags: Array.isArray(req.body.tags) ? req.body.tags.map((tag) => safeText(tag, 30)).slice(0, 10) : [], published: true, createdBy: req.user.id, createdAt: now() }; db.knowledgeBase.unshift(item); addAudit(db, 'knowledge.created', req.user.id, { articleId: item.id }); return item; }); res.status(201).json({ article }); });
  app.patch('/api/admin/knowledge/:id', auth, adminOnly, async (req, res) => { try { const article = await mutateDb((db) => { const item = db.knowledgeBase.find((entry) => entry.id === req.params.id); if (!item) throw new Error('Article not found.'); ['title', 'category', 'summary', 'body'].forEach((field) => { if (req.body[field] !== undefined) item[field] = safeText(req.body[field], field === 'body' ? 5000 : 300); }); if (req.body.published !== undefined) item.published = Boolean(req.body.published); item.updatedAt = now(); return item; }); res.json({ article }); } catch (error) { res.status(404).json({ message: error.message }); } });

  app.get('/api/lost-found/:id/pickups', auth, async (req, res) => { const db = await readDb(); const item = db.lostFound.find((entry) => entry.id === req.params.id); if (!item) return res.status(404).json({ message: 'Item not found.' }); const allowed = item.reporterId === req.user.id || staffRole(req.user.role) || db.claims.some((claim) => claim.itemId === item.id && claim.claimantId === req.user.id && claim.status === 'approved'); if (!allowed) return res.status(403).json({ message: 'Pickup details are private.' }); const pickups = db.pickups.filter((pickup) => pickup.itemId === item.id && (staffRole(req.user.role) || pickup.userId === req.user.id || item.reporterId === req.user.id)).map(({ codeHash, ...pickup }) => pickup); res.json({ pickups, locations: db.settings.pickupLocations }); });
  app.post('/api/lost-found/:id/pickups', auth, async (req, res) => { const scheduled = futureDate(req.body.scheduledAt); if (!scheduled) return res.status(400).json({ message: 'Choose a future pickup date and time.' }); try { const result = await mutateDb((db) => { const item = db.lostFound.find((entry) => entry.id === req.params.id); if (!item) throw new Error('Item not found.'); const claim = db.claims.find((entry) => entry.itemId === item.id && entry.claimantId === req.user.id && entry.status === 'approved'); if (item.reporterId !== req.user.id && !claim && !staffRole(req.user.role)) throw new Error('An approved claimant or reporter must schedule this pickup.'); const location = safeText(req.body.location, 120); if (!db.settings.pickupLocations.includes(location)) throw new Error('Choose an approved campus pickup location.'); db.pickups.filter((entry) => entry.itemId === item.id && entry.userId === req.user.id && entry.status === 'scheduled').forEach((entry) => { entry.status = 'rescheduled'; }); const code = String(crypto.randomInt(100000, 1000000)); const pickup = { id: makeId('PUP'), itemId: item.id, userId: req.user.id, scheduledAt: scheduled.toISOString(), location, notes: safeText(req.body.notes, 500), status: 'scheduled', codeHash: digestCode('pending', code, jwtSecret), codeVersion: 1, createdAt: now() }; pickup.codeHash = digestCode(pickup.id, code, jwtSecret); db.pickups.unshift(pickup); notify(db, req.user.id, 'Pickup scheduled', `${item.itemName} is scheduled for collection at ${location}.`, 'lostFound', item.id); addAudit(db, 'pickup.scheduled', req.user.id, { pickupId: pickup.id, itemId: item.id }); return { pickup: { ...pickup, codeHash: undefined }, code, itemName: item.itemName }; }); const qrPayload = `DELTACARE-PICKUP:${result.pickup.id}:${result.code}`; res.status(201).json({ ...result, qrPayload, qr: await QRCode.toDataURL(qrPayload, { width: 240, margin: 1 }) }); } catch (error) { res.status(400).json({ message: error.message }); } });
  app.get('/api/admin/pickups', auth, adminOnly, async (_req, res) => { const db = await readDb(); res.json({ pickups: db.pickups.map(({ codeHash, ...pickup }) => ({ ...pickup, item: db.lostFound.find((item) => item.id === pickup.itemId)?.itemName, user: db.users.find((user) => user.id === pickup.userId)?.name })), locations: db.settings.pickupLocations }); });
  app.post('/api/admin/pickups/:id/verify', auth, adminOnly, async (req, res) => { try { const result = await mutateDb((db) => { const pickup = db.pickups.find((item) => item.id === req.params.id); if (!pickup || pickup.status !== 'scheduled') throw new Error('This pickup is not active.'); const raw = safeText(req.body.code, 80); const code = raw.startsWith('DELTACARE-PICKUP:') ? raw.split(':').pop() : raw; if (!timingEqual(pickup.codeHash, digestCode(pickup.id, code, jwtSecret))) throw new Error('The one-time collection code is incorrect.'); pickup.status = 'completed'; pickup.verifiedBy = req.user.id; pickup.completedAt = now(); const item = db.lostFound.find((entry) => entry.id === pickup.itemId); if (item) { item.status = 'returned'; item.updatedAt = now(); db.custodyEvents.push({ id: makeId('CST'), itemId: item.id, action: 'released_with_otp', from: pickup.location, to: pickup.userId, actorId: req.user.id, createdAt: now() }); } notify(db, pickup.userId, 'Item collected', `${item?.itemName || 'Your item'} was handed over successfully.`, 'lostFound', pickup.itemId); addAudit(db, 'pickup.completed', req.user.id, { pickupId: pickup.id, itemId: pickup.itemId }); return { pickup: { ...pickup, codeHash: undefined }, item }; }); pushUser(result.pickup.userId, { title: 'Item collected', body: `${result.item?.itemName || 'Your item'} was handed over successfully.`, url: `/app/lost-found/${result.pickup.itemId}` }).catch(() => {}); res.json(result); } catch (error) { res.status(400).json({ message: error.message }); } });
  app.patch('/api/admin/pickups/:id', auth, adminOnly, async (req, res) => { try { const pickup = await mutateDb((db) => { const item = db.pickups.find((entry) => entry.id === req.params.id); if (!item) throw new Error('Pickup not found.'); if (req.body.status === 'cancelled') item.status = 'cancelled'; if (req.body.scheduledAt) { const date = futureDate(req.body.scheduledAt); if (!date) throw new Error('Choose a future pickup time.'); item.scheduledAt = date.toISOString(); item.status = 'scheduled'; } item.updatedAt = now(); notify(db, item.userId, 'Pickup updated', `Your collection appointment is now ${item.status}.`, 'lostFound', item.itemId); return { ...item, codeHash: undefined }; }); res.json({ pickup }); } catch (error) { res.status(400).json({ message: error.message }); } });

  app.post('/api/admin/issues/:id/evidence', auth, adminOnly, async (req, res) => { if (!['before', 'after'].includes(req.body.stage)) return res.status(400).json({ message: 'Evidence stage must be before or after.' }); try { const evidence = await mutateDb((db) => { const issue = db.issues.find((item) => item.id === req.params.id); if (!issue) throw new Error('Issue not found.'); const attachments = cleanAttachments(req.body.attachments); if (!attachments.length) throw new Error('Add at least one evidence photo.'); const item = { id: makeId('EVD'), stage: req.body.stage, note: safeText(req.body.note, 1000), attachments, actorId: req.user.id, createdAt: now() }; issue.evidence = issue.evidence || []; issue.evidence.push(item); attachments.forEach((attachment) => db.jobs.push({ id: makeId('JOB'), type: 'security_scan_and_ocr', entityId: issue.id, attachmentId: attachment.id, status: 'queued', retryCount: 0, createdAt: now() })); addAudit(db, 'issue.evidence_added', req.user.id, { issueId: issue.id, evidenceId: item.id, stage: item.stage }); return item; }); res.status(201).json({ evidence }); } catch (error) { res.status(400).json({ message: error.message }); } });

  app.get('/api/search/advanced', auth, async (req, res) => { const db = await readDb(); const query = safeText(req.query.q, 150).toLowerCase(); const terms = query.split(/\s+/).filter(Boolean); const from = req.query.dateFrom ? new Date(req.query.dateFrom) : null; const to = req.query.dateTo ? new Date(`${req.query.dateTo}T23:59:59`) : null; const accepts = (item, type) => { const searchText = type === 'issue' ? `${item.id} ${item.title} ${item.description} ${item.location} ${item.category} ${(item.attachments || []).map((a) => a.ocr?.text).join(' ')}` : `${item.id} ${item.itemName} ${item.description} ${item.location} ${item.category} ${item.color || ''} ${item.brand || ''} ${(item.attachments || []).map((a) => a.ocr?.text).join(' ')}`; const created = new Date(item.createdAt); return (!terms.length || terms.every((term) => searchText.toLowerCase().includes(term))) && (!req.query.type || req.query.type === type) && (!req.query.status || req.query.status === item.status) && (!req.query.category || req.query.category === item.category) && (!req.query.location || item.location.toLowerCase().includes(String(req.query.location).toLowerCase())) && (!from || created >= from) && (!to || created <= to); }; const issueAllowed = db.issues.filter((item) => item.reporterId === req.user.id || staffRole(req.user.role)); const itemAllowed = db.lostFound.filter((item) => staffRole(req.user.role) || item.reporterId === req.user.id || !['returned', 'closed'].includes(item.status)); const results = [...issueAllowed.filter((item) => accepts(item, 'issue')).map((item) => ({ type: 'issue', id: item.id, title: item.title, excerpt: item.description.slice(0, 180), location: item.location, coordinates: item.coordinates, category: item.category, status: item.status, createdAt: item.createdAt, url: staffRole(req.user.role) ? `/admin/issues/${item.id}` : `/app/issues/${item.id}` })), ...itemAllowed.filter((item) => accepts(item, 'lostFound')).map((item) => ({ type: 'lostFound', id: item.id, title: item.itemName, excerpt: item.description.slice(0, 180), location: item.location, coordinates: item.coordinates, category: item.category, status: item.status, createdAt: item.createdAt, url: staffRole(req.user.role) ? `/admin/items/${item.id}` : `/app/lost-found/${item.id}` }))].sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)).slice(0, 100); res.json({ results, total: results.length }); });

  app.get('/api/reminders', auth, async (req, res) => { const created = await mutateDb((db) => runReminders(db)); const db = await readDb(); const newReminders = db.reminders.filter((item) => created.includes(item.dedupeKey)); newReminders.forEach((item) => pushUser(item.userId, { title: item.title, body: item.message, url: item.entityType === 'issue' ? `/app/issues/${item.entityId}` : `/app/lost-found/${item.entityId}`, tag: item.dedupeKey }).catch(() => {})); res.json({ reminders: db.reminders.filter((item) => item.userId === req.user.id).slice(0, 100) }); });
  app.post('/api/admin/reminders/run', auth, adminOnly, async (req, res) => { const created = await mutateDb((db) => runReminders(db)); const db = await readDb(); db.reminders.filter((item) => created.includes(item.dedupeKey)).forEach((item) => pushUser(item.userId, { title: item.title, body: item.message, url: item.entityType === 'issue' ? `/app/issues/${item.entityId}` : `/app/lost-found/${item.entityId}`, tag: item.dedupeKey }).catch(() => {})); res.json({ created: created.length }); });
  app.get('/api/admin/operations', auth, adminOnly, async (_req, res) => { const db = await readDb(); const email = db.communications.filter((record) => record.channels?.includes('email') || record.deliveries?.some((delivery) => delivery.channel === 'email')).slice(0, 100); res.json({ pickups: db.pickups.map(({ codeHash, ...pickup }) => pickup), reminders: db.reminders.slice(0, 100), communications: email, backups: db.backups, knowledge: db.knowledgeBase, securityEvents: db.securityEvents.slice(0, 100), configuration: { push: vapidReady, smtp: Boolean(process.env.SMTP_HOST && process.env.SMTP_FROM), database: 'Local JSON database', uploads: process.env.UPLOAD_PROVIDER || 'inline', antivirus: process.env.CLAMAV_HOST ? 'ClamAV configured' : 'built-in signature checks', scheduledBackups: Number(process.env.AUTO_BACKUP_HOURS || 0) } }); });
  app.post('/api/admin/communications/:id/retry', auth, adminOnly, async (req, res) => { const db = await readDb(); const record = db.communications.find((item) => item.id === req.params.id); const recipient = record && db.users.find((item) => item.id === record.recipientId); if (!record || !recipient) return res.status(404).json({ message: 'Delivery record or recipient not found.' }); const delivery = await sendEmailMessage({ to: recipient.email, subject: record.subject, body: record.body, actionPath: record.entityType === 'issue' ? `/app/issues/${record.entityId}` : `/app/lost-found/${record.entityId}` }); await mutateDb((latest) => { const item = latest.communications.find((entry) => entry.id === record.id); item.deliveries = item.deliveries || []; item.deliveries.unshift({ channel: 'email', ...delivery, retriedAt: now(), retriedBy: req.user.id }); addAudit(latest, 'email.delivery_retried', req.user.id, { communicationId: item.id, status: delivery.status }); }); res.json({ delivery }); });
}

export { articleDefaults };
